#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/emoji/.env"

##? Pick an emoji using rofi
##?
##? Requirements:
##?     rofi, xsel, xdotool
##?
##? Usage:
##?    pick
##?
##? Notes:
##?     - A font that supports emoji like "Noto Emoji" or "EmojiOne" is needed.
##?     - Ctrl+C in rofi will copy it to the clipboard.
docs::parse "$@"

function notify() {
    if [ "$(command -v notify-send)" ]; then
        notify-send "$1" "$2"
    fi
}

function display() {
    emoji=$(cat "$EMOJI_FILE" | grep -v '#' | grep -v '^[[:space:]]*$')
    line=$(echo "$emoji" | rofi -font "Monospace 30" -theme Monokai -dmenu -i -p emoji -kb-custom-1 Ctrl+c $@)
    exit_code=$?

    line=($line)

    if [ $exit_code == 0 ]; then
        sleep 0.1	# Delay pasting so the text-entry can come active
        xdotool type --clearmodifiers "${line[0]}"
    elif [ $exit_code == 10 ]; then
        echo -n "${line[0]}" | xsel -i -b
    fi
}

# Download all emoji if they don't exist yet
if [ ! -f "$EMOJI_FILE" ]; then
    dot emoji download
fi

display
