#!/bin/bash

MAIN_LEFT=calendar.google.com/calendar/u/0/r/day
MAIN_RIGHT=meet.google.com/kig-rayq-hrz
LAPTOP=www.notion.so/codelytv/db0147cf2ee6416eb930025008aab51b?v=7936e50bc4254ad4a67af0bc214a61a8

google-chrome --profile-directory="Default" --new-window $MAIN_RIGHT && \
xdotool key super+Shift+Left && \
xdotool key super+Right && \
google-chrome --profile-directory="Default" --new-window $LAPTOP && \
xdotool key super+Shift+Right && \
xdotool key super+Up && \
google-chrome --profile-directory="Default" --new-window $MAIN_LEFT && \
xdotool key super+Shift+Left && \
xdotool key super+Left
