#!/bin/env bash

todoist_project_id="2300441446"
tasks=$(todoist tasks list --project=$todoist_project_id)
output_file="$HOME/Insync/santaka87@gmail.com/🧠 Obsidian/PKM/📔 Productivity/👷 Tasks.md"

echo "$tasks" | jq -c '.[]' | while read -r line; do
  id=$(echo "$line" | jq -r '.id')
  content=$(echo "$line" | jq -r '.content')

  echo "$content"
  echo "- [ ] $content" >> "$output_file"

  curl -sf -X POST "https://api.todoist.com/rest/v2/tasks/$id/close" -H "Authorization: Bearer $TODOIST_TOKEN"
done

